sudo: false
language: go
go:
- 1.8
script: go test ./...
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
branches:
  only:
  - master
  - stu3_mar2016
  - stu3_aug2016
  - stu3_jan2017
  - stu3_mar2017
notifications:
  slack:
    secure: Sz0HRgIE23pnsneB/jfKP01E2mRLgPUO72bIiCpTkeRZs3GeMso+eijCDSNwiR+429jK0/LlJhMS2c6CqQDuluMk+GvmQuRgqmj7kB0FDGqCqPpPeU7SsotOt27NRa73nyz8wj1ffmSitvL5emjrZsSIS4nIQF6GEobRI1p3xbY=
